### ISSUE TITLE
[Errno 2] No such file or directory: '/storage/.kodi/userdata/addon_data/script.library.integration.tool/.version'

### ISSUE THREAD

**Issue by Megachip** [patrick-klein/script.library.integration.tool#7]
```
2020-04-19 00:48:48.995 T:1530082160   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno 2] No such file or directory: '/storage/.kodi/userdata/addon_data/script.library.integration.tool/.version'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.library.integration.tool/context2.py", line 45, in <module>
                                                main()
                                              File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/utils.py", line 190, in wrapper
                                                check_version_file()
                                              File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/utils.py", line 179, in check_version_file
                                                with open(version_file_path, 'w') as version_file:
                                            IOError: [Errno 2] No such file or directory: '/storage/.kodi/userdata/addon_data/script.library.integration.tool/.version'
                                            -->End of Python script error report<--
```

**Comment by david-morris** [comment]
Hi, I have also got this error under Leia running Arch Linux.

```
2020-07-01 13:13:41.988 T:140637227710208   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno 2] No such file or directory: '/var/lib/kodi/.kodi/userdata/addon_data/script.library.integration.tool/.version'
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/script.library.integration.tool/default.py", line 30, in <module>
                                                main()
                                              File "/var/lib/kodi/.kodi/addons/script.library.integration.tool/resources/lib/utils.py", line 190, in wrapper
                                                check_version_file()
                                              File "/var/lib/kodi/.kodi/addons/script.library.integration.tool/resources/lib/utils.py", line 179, in check_version_file
                                                with open(version_file_path, 'w') as version_file:
                                            IOError: [Errno 2] No such file or directory: '/var/lib/kodi/.kodi/userdata/addon_data/script.library.integration.tool/.version'
                                            -->End of Python script error report<--
```


I notice I'm missing that userdata folder. The file doesn't seem to matter, but creating the folder lets the addon generate the directory structure to add to the library.

**Comment by luizoti** [comment]
fix 93c785c

**Comment by luizoti** [comment]
fix 8611a00, 93c785c
